# -*- coding: utf-8 -*-
"""Dữ liệu cho Trợ lý code: cờ đặc điểm bài, lỗi riêng từng bài (regex), gợi ý tối ưu.
flags: ll = cần long long, neg = có số âm (khởi tạo max = 0 sai), mod = in kết quả mod,
       big_input = input lớn (cần đọc nhanh), big_value = giá trị tới 1e12+.
opt.slow: các hướng làm bị coi là chậm với bài này (nested, nested3, recursion, perm, subset, linear).
"""

HINTS = {
"cx_01": {"flags": {"ll": True, "big_input": True, "big_value": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Công thức O(1)",
    "idea": "Không cần duyệt từng số: số bội của k trong [1, x] là x / k. Vì vậy đáp án = b/k − (a−1)/k.",
    "code": "long long a, b, k;\ncin >> a >> b >> k;\ncout << b / k - (a - 1) / k << '\\n';",
    "why": "Vòng for từ a đến b chạy tới 10⁹–10¹⁸ lần mỗi truy vấn; công thức chỉ 2 phép chia → O(1), T = 10⁵ truy vấn vẫn tức thì."},
  "rules": [{"re": r"b\s*/\s*k\s*-\s*a\s*/\s*k", "title": "Thiếu −1: đếm sai khi a là bội của k",
    "why": "b/k − a/k bỏ mất chính số a nếu a chia hết cho k (ví dụ a=6, b=6, k=3 cho 0 thay vì 1).",
    "fix": "b / k - (a - 1) / k", "better": "Số bội trong [a, b] = (bội trong [1, b]) − (bội trong [1, a−1])."}]},
"cx_02": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Đếm theo số dư O(n + k)",
    "idea": "aᵢ + aⱼ chia hết k ⇔ (aᵢ mod k) + (aⱼ mod k) ∈ {0, k}. Đếm cnt[r] rồi ghép dư r với dư k−r.",
    "code": "vector<long long> cnt(k);\nfor (x : a) cnt[x % k]++;\nans = cnt[0]*(cnt[0]-1)/2;\nfor (r = 1; r < k - r; r++) ans += cnt[r]*cnt[k-r];\nif (k % 2 == 0) ans += cnt[k/2]*(cnt[k/2]-1)/2;",
    "why": "Thay vì xét n²/2 ≈ 2·10¹⁰ cặp, chỉ cần 1 lần duyệt dãy + 1 lần duyệt số dư."},
  "rules": []},
"cx_03": {"flags": {"ll": True, "big_value": True},
  "opt": {"slow": ["nested"], "name": "Duyệt ước tới √n O(√n)",
    "idea": "Ước đi theo cặp (d, n/d), một trong hai luôn ≤ √n. Chỉ cần d chạy tới khi d·d > n.",
    "code": "for (long long d = 1; d * d <= n; d++)\n    if (n % d == 0) cnt += (d == n / d) ? 1 : 2;",
    "why": "n = 10¹² thì duyệt tới n mất 10¹² bước (hàng giờ), còn tới √n chỉ 10⁶ bước."},
  "rules": [{"re": r"cnt\s*\+=\s*2\s*;", "sev": "warn", "title": "Số chính phương bị đếm ước √n hai lần",
    "why": "Khi d = n/d (ví dụ n = 36, d = 6) thì chỉ có 1 ước chứ không phải 2.",
    "fix": "cnt += (d == n / d) ? 1 : 2;", "better": "Kiểm tra d == n/d trước khi cộng 2."}]},
"pf_01": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Mảng cộng dồn (prefix sum)",
    "idea": "Dựng p[i] = a₁+…+aᵢ một lần, mỗi truy vấn tổng [l, r] = p[r] − p[l−1].",
    "code": "vector<long long> p(n + 1, 0);\nfor (int i = 1; i <= n; i++) p[i] = p[i-1] + a[i];\n// truy vấn:\ncout << p[r] - p[l - 1] << '\\n';",
    "why": "Vòng for cộng từng phần tử cho mỗi truy vấn tốn O(n·q) = 4·10¹⁰. Prefix tốn O(n) dựng + O(1) mỗi truy vấn → O(n + q)."},
  "rules": [{"re": r"\bp\s*\[\s*r\s*\]\s*-\s*p\s*\[\s*l\s*\]", "title": "Lệch chỉ số: thiếu phần tử a[l]",
    "why": "p[r] − p[l] là tổng a[l+1..r], thiếu a[l]. Thử với l = r sẽ ra 0.",
    "fix": "p[r] - p[l - 1]", "better": "p[l−1] là tổng các phần tử TRƯỚC l nên trừ đi là còn đúng đoạn [l, r]."}]},
"pf_02": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Prefix sum + map đếm",
    "idea": "Tổng [l, r] = K ⇔ p[l−1] = p[r] − K. Duyệt r, đếm số lần giá trị p[r]−K đã xuất hiện trong map.",
    "code": "map<long long, long long> cnt; cnt[0] = 1;\nlong long p = 0, ans = 0;\nfor (x : a) { p += x; ans += cnt[p - K]; cnt[p]++; }",
    "why": "Thay vì thử mọi cặp (l, r) O(n²), mỗi r chỉ tra map O(log n) → O(n log n)."},
  "rules": [{"if": r"map\s*<", "absent": r"\[\s*0\s*\]\s*=\s*1|\[\s*0\s*\]\s*\+\+|\[\s*0\s*\]\s*\+=\s*1", "title": "Quên cnt[0] = 1",
    "why": "p[0] = 0 cũng là một tiền tố. Thiếu nó thì mọi đoạn bắt đầu từ vị trí 1 bị bỏ sót.",
    "fix": "cnt[0] = 1;   // trước vòng for", "better": "Coi như đã 'thấy' tổng tiền tố 0 trước khi đọc phần tử nào."},
   {"re": r"while\s*\([^)]*>\s*K", "sev": "warn", "title": "Two pointers sai khi có số âm",
    "why": "Cửa sổ trượt chỉ đúng khi mọi số dương. Đề cho aᵢ âm nên co cửa sổ có thể bỏ lỡ đáp án.",
    "fix": "// dùng prefix sum + map thay vì two pointers", "better": "Prefix + map không phụ thuộc dấu của aᵢ."}]},
"pf_03": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Mảng hiệu (difference array)",
    "idea": "Mỗi lần tưới chỉ ghi d[l] += x; d[r+1] −= x. Cuối cùng cộng dồn d một lần.",
    "code": "vector<long long> d(n + 2, 0);\nd[l] += x; d[r + 1] -= x;   // mỗi lần tưới\nlong long add = 0;\nfor (i = 1..n) { add += d[i]; a[i] += add; }",
    "why": "Cộng x vào từng cây mất O(n) mỗi lần → O(n·m) = 4·10¹⁰; mảng hiệu O(1) mỗi lần → O(n + m)."},
  "rules": [{"re": r"\bd\s*\[\s*r\s*\]\s*-=", "title": "Trừ sai vị trí: phải là d[r+1]",
    "why": "d[r] −= x làm cây thứ r không được cộng.", "fix": "d[r + 1] -= x;", "better": "Hiệu lực cộng kéo dài tới hết r rồi mới tắt ở r+1."}]},
"pf_04": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["nested3"], "name": "Prefix sum 2D",
    "idea": "S[i][j] = a[i][j] + S[i−1][j] + S[i][j−1] − S[i−1][j−1]; mỗi truy vấn dùng 4 ô S.",
    "code": "ans = S[x2][y2] - S[x1-1][y2] - S[x2][y1-1] + S[x1-1][y1-1];",
    "why": "Cộng từng ô trong hình chữ nhật mất O(n·m) mỗi truy vấn; prefix 2D chỉ O(1)."},
  "rules": [{"if": r"S\s*\[\s*x2\s*\]\s*\[\s*y2\s*\]", "absent": r"\+\s*S\s*\[\s*x1\s*-\s*1\s*\]\s*\[\s*y1\s*-\s*1\s*\]", "title": "Quên cộng lại góc S[x1−1][y1−1]",
    "why": "Góc trên trái bị trừ 2 lần (trong dải trên và dải trái) nên phải cộng lại 1 lần.",
    "fix": "+ S[x1 - 1][y1 - 1]", "better": "Nguyên lý bao hàm – loại trừ."}]},
"bs_01": {"flags": {"big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Sort + lower_bound/upper_bound",
    "idea": "Sort một lần; số phần tử trong [x, y] = upper_bound(y) − lower_bound(x).",
    "code": "sort(a.begin(), a.end());\ncout << upper_bound(a.begin(), a.end(), y) - lower_bound(a.begin(), a.end(), x);",
    "why": "Đếm bằng vòng for là O(n) mỗi truy vấn → O(n·q); tìm nhị phân chỉ O(log n)."},
  "rules": [{"if": r"lower_bound|upper_bound", "absent": r"\bsort\s*\(", "title": "Chưa sort trước khi tìm nhị phân",
    "why": "lower_bound/upper_bound chỉ đúng trên dãy đã sắp tăng dần.", "fix": "sort(a.begin(), a.end());", "better": "Sort 1 lần O(n log n), sau đó mọi truy vấn đều nhị phân được."}]},
"bs_02": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Chặt nhị phân theo kết quả L",
    "idea": "L càng lớn thì càng ít thanh → điều kiện đơn điệu. Nhị phân L trong [1, max a], mỗi lần kiểm tra O(n).",
    "code": "long long lo = 1, hi = maxA, ans = 0;\nwhile (lo <= hi) {\n    long long mid = (lo + hi) / 2;\n    if (ok(mid)) { ans = mid; lo = mid + 1; } else hi = mid - 1;\n}",
    "why": "Thử mọi L tốn O(max·n) = 10⁹·n; nhị phân chỉ ~30 lần kiểm tra → O(30·n)."},
  "rules": []},
"bs_03": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["nested"], "slow_re": r"priority_queue", "slow_name": "Mô phỏng từng bản in bằng priority_queue", "slow_cx": "O(m log n), m tới 10⁹", "name": "Chặt nhị phân thời gian T",
    "idea": "Trong T giây in được Σ ⌊T/tᵢ⌋ bản – tăng theo T. Nhị phân T nhỏ nhất đủ m bản.",
    "code": "bool ok(long long T) {\n    long long c = 0;\n    for (x : t) { c += T / x; if (c >= m) return true; }\n    return false;\n}",
    "why": "Mô phỏng từng bản in tốn O(m log n) với m tới 10⁹; nhị phân chỉ ~60·n phép."},
  "rules": [{"if": r"\+=\s*\w+\s*/\s*\w+\s*;", "absent": r"return\s+true|break", "sev": "warn", "title": "Tổng có thể vượt long long – nên dừng sớm",
    "why": "Với T ~ 10¹⁸ và nhiều máy tᵢ = 1, Σ T/tᵢ vượt 9,2·10¹⁸ và bị tràn thành số âm.",
    "fix": "if (c >= m) return true;   // ngay trong vòng for", "better": "Đủ m rồi thì không cần cộng tiếp, số không bao giờ tràn."}]},
"tp_01": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Hai con trỏ / cửa sổ co giãn",
    "idea": "Số dương nên khi r tăng thì l không bao giờ phải lùi. Thêm a[r], nếu tổng > S thì bỏ a[l], l++.",
    "code": "for (int r = 0; r < n; r++) {\n    sum += a[r];\n    while (sum > S) sum -= a[l++];\n    best = max(best, r - l + 1);\n}",
    "why": "Mỗi phần tử vào 1 lần, ra 1 lần → O(n) thay vì O(n²)."},
  "rules": []},
"tp_02": {"flags": {"ll": True, "neg": True, "big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Cửa sổ trượt kích thước k",
    "idea": "Tổng cửa sổ mới = tổng cũ + a[i] − a[i−k].",
    "code": "for (i = k; i < n; i++) { sum += a[i] - a[i-k]; best = max(best, sum); }",
    "why": "Tính lại tổng k phần tử mỗi lần tốn O(n·k); cập nhật 2 phần tử chỉ O(1) → O(n)."},
  "rules": []},
"tp_03": {"flags": {"big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Cửa sổ trượt + map đếm màu",
    "idea": "Giữ map cnt các màu trong [l, r]. Khi cnt.size() > K thì bỏ a[l], xóa màu khỏi map nếu về 0.",
    "code": "cnt[a[r]]++;\nwhile (cnt.size() > K) { if (--cnt[a[l]] == 0) cnt.erase(a[l]); l++; }",
    "why": "O(n log n) thay vì dựng set lại cho mọi đoạn O(n² log n)."},
  "rules": [{"if": r"\bcnt\s*\.\s*size\s*\(\s*\)\s*>\s*K", "absent": r"\.erase\s*\(", "title": "Quên xóa màu có số đếm 0 khỏi map",
    "why": "cnt.size() vẫn đếm cả màu đã ra khỏi cửa sổ (số đếm 0), nên số màu bị tính sai.",
    "fix": "if (--cnt[a[l]] == 0) cnt.erase(a[l]);", "better": "map chỉ chứa các màu thực sự còn trong cửa sổ."}]},
"nt_01": {"flags": {"ll": True, "big_input": True, "big_value": True},
  "opt": {"slow": ["nested"], "name": "Thuật toán Euclid",
    "idea": "gcd(a, b) = gcd(b, a mod b) — mỗi bước số giảm rất nhanh (O(log)).",
    "code": "long long g = __gcd(a, b);\nlong long l = a / g * b;",
    "why": "Thử mọi ước từ min(a,b) xuống tốn tới 10¹⁸ bước; Euclid chỉ ~90 bước."},
  "rules": []},
"nt_02": {"flags": {"big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Sàng Eratosthenes + prefix",
    "idea": "Sàng một lần tới 10⁷, dựng cnt[i] = số nguyên tố ≤ i; mỗi câu hỏi = cnt[r] − cnt[l−1].",
    "code": "for (i = 2; i * i <= N; i++) if (!comp[i])\n    for (j = i * i; j <= N; j += i) comp[j] = true;\nfor (i = 1; i <= N; i++) cnt[i] = cnt[i-1] + !comp[i];",
    "why": "Kiểm tra từng số trong mỗi đoạn tốn O(q·N·√N); sàng O(N log log N) + O(1) mỗi câu."},
  "rules": [{"if": r"j\s*\+=\s*i", "absent": r"\[\s*1\s*\]\s*=\s*(true|1)|\[\s*0\s*\]\s*=\s*\w+\s*\[\s*1\s*\]|<\s*2", "title": "Chưa đánh dấu 1 không phải số nguyên tố",
    "why": "Sàng bắt đầu từ 2 nên số 1 vẫn được coi là nguyên tố; mọi đoạn chứa 1 bị đếm thừa.",
    "fix": "comp[0] = comp[1] = true;", "better": "Số nguyên tố phải > 1 theo định nghĩa."}]},
"nt_03": {"flags": {"ll": True, "big_input": True, "big_value": True, "mod": True},
  "opt": {"slow": ["nested"], "name": "Lũy thừa nhanh O(log b)",
    "idea": "aᵇ = (a^(b/2))² nếu b chẵn; mỗi bước bình phương a và chia đôi b.",
    "code": "a %= MOD; long long r = 1;\nwhile (b > 0) { if (b & 1) r = r * a % MOD; a = a * a % MOD; b >>= 1; }",
    "why": "Nhân b lần tốn tới 10¹⁸ phép; lũy thừa nhanh chỉ ~60 phép."},
  "rules": [{"if": r"b\s*>>=\s*1|b\s*/=\s*2", "absent": r"\ba\s*%=|\ba\s*=\s*a\s*%", "title": "Quên a %= MOD trước khi bình phương",
    "why": "a tới 10¹⁸ thì a*a tới 10³⁶, tràn long long ngay ở bước đầu.",
    "fix": "a %= MOD;   // trước vòng while", "better": "Sau khi mod, a < 10⁹+7 nên a*a < 1,1·10¹⁸ vừa long long."}]},
"gr_01": {"flags": {"big_input": True},
  "opt": {"slow": ["subset", "recursion", "nested"], "name": "Tham lam theo thời điểm kết thúc",
    "idea": "Sort theo e tăng dần; chọn cuộc họp nếu s ≥ lastEnd.",
    "code": "sort theo (e, s);\nfor (m : a) if (m.s >= lastEnd) { cnt++; lastEnd = m.e; }",
    "why": "Thử mọi tập con O(2ⁿ) chỉ chạy được n ≤ 20; tham lam O(n log n). Chọn cuộc kết thúc sớm nhất luôn chừa nhiều thời gian nhất cho phần còn lại."},
  "rules": [{"re": r"\.s\s*>\s*lastEnd|\bs\s*>\s*lastEnd", "title": "Dùng > thay vì >=",
    "why": "Đề cho phép cuộc họp bắt đầu đúng lúc cuộc trước kết thúc.", "fix": "s >= lastEnd", "better": "Bao gồm cả trường hợp nối đuôi."}]},
"gr_02": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["perm", "recursion", "nested"], "name": "Sort tăng dần (người nhanh trước)",
    "idea": "Người ở vị trí k làm n−k+1 người chờ thêm tᵢ ⇒ thời gian nhỏ nên đứng trước.",
    "code": "sort(t.begin(), t.end());\nfor (x : t) { now += x; total += now; }",
    "why": "Thử mọi hoán vị O(n!) chỉ được n ≤ 10; sort O(n log n)."},
  "rules": [{"re": r"rbegin|greater\s*<", "title": "Sắp xếp giảm dần là sai",
    "why": "Người làm lâu đứng trước khiến tất cả người sau phải chờ lâu.", "fix": "sort(t.begin(), t.end());", "better": "Tăng dần mới cho tổng nhỏ nhất (lập luận đổi chỗ 2 người kề nhau)."}]},
"gr_03": {"flags": {"big_input": True},
  "opt": {"slow": ["recursion", "subset", "perm", "nested"], "name": "Sort + hai con trỏ (nặng nhất + nhẹ nhất)",
    "idea": "Người nặng nhất chắc chắn đi; cho đi cùng người nhẹ nhất nếu vừa, không thì đi một mình.",
    "code": "sort(w);\nwhile (i <= j) { if (i < j && w[i] + w[j] <= C) i++; j--; boats++; }",
    "why": "O(n log n) thay vì thử mọi cách ghép (hàm mũ)."},
  "rules": [{"re": r"w\s*\[\s*i\s*\]\s*\+\s*w\s*\[\s*i\s*\+\s*1\s*\]", "title": "Ghép 2 người đứng cạnh nhau là tham lam sai",
    "why": "Ví dụ C=10, w = 1 2 8 9: ghép cạnh nhau ra (1,2),(8),(9) = 3 thuyền, tối ưu là (1,9),(2,8) = 2.",
    "fix": "if (w[i] + w[j] <= C) i++;  // nhẹ nhất + nặng nhất", "better": "Người nặng nhất cần bạn đi kèm nhẹ nhất có thể."}]},
"dp_01": {"flags": {"ll": True, "neg": True, "big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Kadane O(n)",
    "idea": "f[i] = max(a[i], f[i−1] + a[i]): nối tiếp đoạn cũ hoặc bắt đầu lại tại i.",
    "code": "long long cur = a[0], best = a[0];\nfor (i = 1; i < n; i++) { cur = max(a[i], cur + a[i]); best = max(best, cur); }",
    "why": "Thử mọi đoạn O(n²); Kadane mỗi phần tử xét 1 lần."},
  "rules": [{"re": r"max\s*\(\s*0(LL)?\s*,", "title": "max(0, ...) cho phép đoạn rỗng",
    "why": "Đề yêu cầu đoạn khác rỗng; toàn số âm thì đáp án phải âm chứ không phải 0.",
    "fix": "cur = max(a[i], cur + a[i]);", "better": "Luôn giữ ít nhất 1 phần tử trong đoạn."}]},
"dp_02": {"flags": {"mod": True, "big_input": False},
  "opt": {"slow": ["recursion"], "name": "QHĐ trên lưới f[i][j] = f[i−1][j] + f[i][j−1]",
    "idea": "Số đường tới ô = số đường tới ô trên + ô trái; ô '#' bằng 0.",
    "code": "f[i][j] = (g[i][j] == '#') ? 0 : (f[i-1][j] + f[i][j-1]) % MOD;",
    "why": "Đệ quy liệt kê từng đường: số đường tăng theo hàm mũ (lưới 1000×1000 có >600 chữ số). QHĐ mỗi ô tính 1 lần → O(n·m)."},
  "rules": []},
"dp_03": {"flags": {"big_input": True},
  "opt": {"slow": ["recursion"], "name": "QHĐ 1 chiều O(n·K)",
    "idea": "f[i] = min(f[j] + |h[j] − h[i]|) với i−K ≤ j < i.",
    "code": "f[1] = 0;\nfor (i = 2; i <= n; i++)\n    for (j = max(1, i - K); j < i; j++) f[i] = min(f[i], f[j] + abs(h[j] - h[i]));",
    "why": "Đệ quy không nhớ tính lại cùng một hòn đá rất nhiều lần (hàm mũ). Lưu f[i] thì mỗi hòn tính 1 lần."},
  "rules": []},
"dp_04": {"flags": {"ll": True},
  "opt": {"slow": ["recursion", "subset"], "name": "QHĐ cái túi dp[j], j giảm dần",
    "idea": "dp[j] = giá trị lớn nhất với khối lượng ≤ j. Với mỗi món: j từ W xuống w.",
    "code": "for (j = W; j >= w; j--) dp[j] = max(dp[j], dp[j - w] + v);",
    "why": "Thử mọi tập con O(2ⁿ) với n = 100 là không thể; QHĐ O(n·W) = 10⁷."},
  "rules": [{"re": r"for\s*\(\s*int\s+j\s*=\s*w\s*;\s*j\s*<=", "title": "Duyệt j tăng dần → một món bị lấy nhiều lần",
    "why": "dp[j − w] đã được cập nhật bằng chính món này ở bước trước nên món bị cộng lặp.",
    "fix": "for (int j = W; j >= w; j--)", "better": "Giảm dần thì dp[j − w] vẫn là giá trị 'chưa có món i'."}]},
"dp_05": {"flags": {"big_input": True},
  "opt": {"slow": ["nested", "subset", "recursion"], "name": "LIS O(n log n) với lower_bound",
    "idea": "tail[k] = phần tử cuối nhỏ nhất của dãy tăng dài k+1; với mỗi x thay tail ở lower_bound(x).",
    "code": "auto it = lower_bound(tail.begin(), tail.end(), x);\nif (it == tail.end()) tail.push_back(x); else *it = x;",
    "why": "O(n²) chỉ chạy được n ≤ 5000 (70 điểm); n = 2·10⁵ cần O(n log n)."},
  "rules": [{"re": r"upper_bound", "title": "upper_bound tính dãy KHÔNG GIẢM",
    "why": "Đề yêu cầu tăng ngặt; upper_bound cho phép nối số bằng nhau.", "fix": "lower_bound(tail.begin(), tail.end(), x)", "better": "lower_bound thay thế phần tử ≥ x nên 2 số bằng nhau không cùng nằm trong dãy."}]},
"dp_06": {"flags": {},
  "opt": {"slow": ["subset", "recursion"], "name": "QHĐ LCS f[i][j]",
    "idea": "s[i] = t[j] ⇒ f[i−1][j−1] + 1, ngược lại max(f[i−1][j], f[i][j−1]).",
    "code": "cur[j] = (s[i-1] == t[j-1]) ? prev[j-1] + 1 : max(prev[j], cur[j-1]);",
    "why": "Thử mọi xâu con O(2ⁿ); QHĐ O(n·m) = 2,5·10⁷."},
  "rules": []},
"st_01": {"flags": {},
  "opt": {"slow": ["nested"], "name": "Mảng đếm 26 chữ cái",
    "idea": "cnt[c − 'a']++ cho mỗi ký tự, rồi tìm max.",
    "code": "int cnt[26] = {0};\nfor (char c : s) cnt[c - 'a']++;",
    "why": "Đếm lại cả xâu cho mỗi vị trí O(n²); mảng đếm O(n)."},
  "rules": [{"re": r">=\s*cnt\s*\[", "title": "Dùng >= nên khi hòa lại chọn chữ lớn hơn",
    "why": "Đề yêu cầu chữ nhỏ nhất khi bằng số lần.", "fix": "if (cnt[k] > cnt[best]) best = k;", "better": "> giữ nguyên chữ nhỏ hơn đã chọn trước."}]},
"st_02": {"flags": {},
  "rules": [{"if": r"s\s*\[\s*l\s*\]\s*==\s*s\s*\[\s*r\s*\]", "absent": r"\w+\s*\+\s*1\s*\)", "sev": "warn", "title": "Có thể chỉ xét tâm độ dài lẻ",
    "why": "Xâu đối xứng độ dài chẵn (như abba) có tâm nằm GIỮA 2 ký tự; chỉ loang từ (c, c) sẽ bỏ sót.",
    "fix": "best = max(best, expand(c, c + 1));", "better": "Xét đủ 2n−1 tâm."}],
  "opt": {"slow": ["nested3"], "name": "Mở rộng từ tâm O(n²)",
    "idea": "Mỗi tâm (1 ký tự hoặc giữa 2 ký tự) loang ra hai bên khi còn bằng nhau.",
    "code": "best = max(best, expand(c, c));     // độ dài lẻ\nbest = max(best, expand(c, c + 1)); // độ dài chẵn",
    "why": "Thử mọi xâu con rồi kiểm tra O(n³) = 1,25·10¹¹; mở rộng từ tâm O(n²)."}},
"st_03": {"flags": {},
  "opt": {"slow": ["nested", "nested3"], "slow_re": r"\bsubstr\s*\(|sort\s*\(\s*sub", "slow_name": "Cắt rồi sort từng xâu con", "slow_cx": "O(n·m log m)", "name": "Cửa sổ trượt + bảng đếm",
    "idea": "Trượt cửa sổ dài |p|: thêm 1 ký tự, bớt 1 ký tự, so sánh 2 mảng 26 phần tử.",
    "code": "win[s[i]-'a']++; win[s[i-m]-'a']--;\nif (win == need) cnt++;",
    "why": "Sort từng cửa sổ O(n·m log m); cửa sổ trượt O(26·n)."},
  "rules": [{"re": r"\bsubstr\s*\(", "sev": "warn", "title": "substr trong vòng lặp tạo xâu mới mỗi lần",
    "why": "Mỗi lần substr tốn O(|p|), lặp n lần → O(n·|p|) có thể tới 10¹¹.", "fix": "// cập nhật bảng đếm khi trượt thay vì cắt xâu", "better": "Chỉ thay đổi 2 ô của bảng đếm mỗi bước."}]},
"gp_01": {"flags": {},
  "opt": {"slow": ["nested3"], "name": "Loang BFS/DFS mỗi vùng một lần",
    "idea": "Gặp ô '.' chưa thăm → đếm vùng mới và BFS đánh dấu cả vùng.",
    "code": "if (g[i][j] == '.' && !vis[i][j]) { regions++; bfs(i, j); }",
    "why": "Lặp 'lan nhãn' tới khi ổn định có thể O((n·m)²); BFS mỗi ô thăm 1 lần → O(n·m)."},
  "rules": [{"re": r"for\s*\(\s*int\s+\w+\s*=\s*-1\s*;[^)]*<=\s*1\s*;[^)]*\)\s*for\s*\(\s*int\s+\w+\s*=\s*-1", "title": "Loang 8 hướng (tính cả ô chéo)",
    "why": "Đề chỉ coi 2 ô kề CẠNH là cùng vùng; chạm góc không tính.", "fix": "int dx[4] = {-1, 1, 0, 0}, dy[4] = {0, 0, -1, 1};", "better": "Đúng định nghĩa kề trong đề."}]},
"gp_02": {"flags": {},
  "opt": {"slow": ["nested3", "recursion"], "name": "BFS từ S",
    "idea": "BFS theo lớp: ô được thăm lần đầu có khoảng cách ngắn nhất.",
    "code": "dist[nx][ny] = dist[x][y] + 1; q.push({nx, ny});",
    "why": "Lặp cập nhật khoảng cách tới khi ổn định có thể O((n·m)²); BFS O(n·m)."},
  "rules": [{"re": r"stack\s*<", "title": "Dùng stack (DFS) không cho đường ngắn nhất",
    "why": "DFS đi sâu theo một hướng nên ô có thể bị gán khoảng cách lớn hơn thực tế.", "fix": "queue<pair<int,int>> q;  // BFS", "better": "Hàng đợi đảm bảo thăm theo thứ tự khoảng cách tăng dần."}]},
"gp_03": {"flags": {"big_input": True},
  "opt": {"slow": ["nested"], "slow_re": r"while\s*\(\s*q\s*--\s*\)\s*\{[^}]*vector\s*<\s*bool\s*>", "slow_name": "BFS lại cho mỗi câu hỏi", "slow_cx": "O(q·(n+m))", "name": "Đánh số thành phần liên thông 1 lần",
    "idea": "BFS từ mỗi đỉnh chưa thăm, gán comp[v] = id; câu hỏi chỉ so comp[u] == comp[v].",
    "code": "for (s = 1..n) if (!comp[s]) { id++; bfs(s, id); }\ncout << (comp[u] == comp[v] ? \"YES\" : \"NO\");",
    "why": "BFS lại cho mỗi câu hỏi O(q·(n+m)) = 8·10¹⁰; đánh số 1 lần O(n + m + q)."},
  "rules": [{"if": r"adj\s*\[\s*a\s*\]\s*\.push_back\s*\(\s*b\s*\)", "absent": r"adj\s*\[\s*b\s*\]\s*\.push_back\s*\(\s*a\s*\)", "title": "Đồ thị vô hướng nhưng chỉ thêm cạnh 1 chiều",
    "why": "a quen b thì b cũng quen a; thiếu chiều ngược làm BFS không đi được từ b sang a.", "fix": "adj[a].push_back(b);\nadj[b].push_back(a);", "better": "Cạnh vô hướng = 2 cạnh có hướng."}]},
"ex_01": {"flags": {"ll": True, "big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Prefix theo số dư + map",
    "idea": "Tổng [l, r] chia hết k ⇔ p[r] ≡ p[l−1] (mod k). Đếm số tiền tố cùng số dư.",
    "code": "p = ((p + a) % k + k) % k;\nans += cnt[p]; cnt[p]++;",
    "why": "O(n log n) thay vì thử mọi đoạn O(n²)."},
  "rules": [{"if": r"\[\s*\w+\s*%\s*k\s*\]|=\s*\(?\s*\w+\s*(\+\s*\w+\s*)?\)?\s*%\s*k\s*;", "absent": r"\+\s*k\s*\)\s*%\s*k", "title": "Số dư âm khi tổng âm",
    "why": "Trong C++, (−1) % 3 = −1 chứ không phải 2, nên −1 và 2 bị coi là 2 số dư khác nhau.", "fix": "((p % k) + k) % k", "better": "Luôn đưa số dư về [0, k−1]."}]},
"ex_02": {"flags": {"big_input": True},
  "opt": {"slow": ["nested", "nested3"], "name": "Chặt nhị phân khoảng cách + tham lam",
    "idea": "Đoán d; đặt bò tham lam từ trái sang (cách con trước ≥ d). Đặt đủ c con → thử d lớn hơn.",
    "code": "while (lo <= hi) { mid = (lo + hi) / 2; if (ok(mid)) { ans = mid; lo = mid + 1; } else hi = mid - 1; }",
    "why": "Thử mọi d tới 10⁹ là quá chậm; nhị phân ~30 lần × O(n)."},
  "rules": [{"if": r"bool\s+ok|lo\s*<=\s*hi", "absent": r"\bsort\s*\(", "title": "Quên sắp xếp tọa độ",
    "why": "Đề cho tọa độ chưa sắp xếp; tham lam đặt bò từ trái sang chỉ đúng khi đã sort.", "fix": "sort(x.begin(), x.end());", "better": ""}]},
"ex_03": {"flags": {"ll": True, "neg": True, "big_input": True},
  "rules": [{"if": r"max\s*\(\s*f\s*\[", "absent": r"LLONG_MIN|-\s*1e18|INF|NEG", "title": "Viền ngoài của bảng f đang là 0, phải là −∞",
    "why": "Mảng toàn cục mặc định bằng 0. Ô ở hàng 1 lấy max(f[0][j], f[1][j−1]) sẽ chọn f[0][j] = 0, tức là coi như đi từ ngoài lưới vào, sai khi có số âm.",
    "fix": "const long long NEG = LLONG_MIN / 4;\nfor (i..) for (j..) f[i][j] = NEG;   // rồi f[1][1] = a[1][1]", "better": "Ô ngoài lưới không bao giờ được chọn vì giá trị cực nhỏ."}],
  "opt": {"slow": ["recursion"], "name": "QHĐ trên lưới f[i][j] = a + max(trên, trái)",
    "idea": "Mỗi ô chỉ đến từ trên hoặc trái; viền ngoài là −∞ (không đi được).",
    "code": "f[i][j] = a[i][j] + max(f[i-1][j], f[i][j-1]);  // viền = -INF, f[1][1] = a[1][1]",
    "why": "Đệ quy thử mọi đường tăng theo hàm mũ; QHĐ O(n·m)."}},
"ex_04": {"flags": {},
  "opt": {"slow": ["nested3"], "name": "BFS nhiều nguồn",
    "idea": "Cho TẤT CẢ ô 'F' vào hàng đợi với thời gian 0 rồi BFS một lần.",
    "code": "for (mọi ô F) { t[i][j] = 0; q.push({i, j}); }\n// BFS như bình thường",
    "why": "Mô phỏng từng phút tốn O(n·m·số phút) có thể 10¹¹; BFS nhiều nguồn O(n·m)."},
  "rules": []},
"bm_01": {"flags": {"ll": True},
  "opt": {"slow": ["recursion", "perm"], "name": "Duyệt mọi tập con bằng bitmask",
    "idea": "mask từ 0 tới 2ⁿ−1; bit i bật ⇔ chọn phần tử i. Có thể tính tổng nhanh: sum[mask] = sum[mask bỏ bit thấp nhất] + a[bit đó].",
    "code": "for (int mask = 0; mask < (1 << n); mask++) {\n    long long s = 0;\n    for (int i = 0; i < n; i++) if (mask >> i & 1) s += a[i];\n    if (s == S) cnt++;\n}",
    "why": "Đệ quy cũng O(2ⁿ) nhưng bitmask ngắn, không tràn stack và dễ kiểm soát."},
  "rules": [{"re": r"mask\s*<=\s*\(?\s*1\s*<<", "title": "mask <= (1 << n) thừa một giá trị",
    "why": "Các tập con là 0 … 2ⁿ−1; mask = 2ⁿ có bit n bật (không tồn tại phần tử n).", "fix": "mask < (1 << n)", "better": ""},
   {"re": r"mask\s*=\s*1\s*;", "sev": "warn", "title": "Bỏ qua tập rỗng (mask = 0)",
    "why": "Nếu S = 0 thì tập rỗng cũng có tổng 0 và phải được đếm.", "fix": "for (int mask = 0; ...)", "better": ""}]},
"bm_02": {"flags": {"ll": True},
  "opt": {"slow": ["perm", "recursion"], "name": "QHĐ bitmask dp[mask]",
    "idea": "dp[mask] = chi phí nhỏ nhất khi các việc trong mask đã giao cho popcount(mask) người đầu tiên.",
    "code": "dp[0] = 0;\nfor (mask = 0; mask < (1 << n); mask++) {\n    int i = __builtin_popcount(mask);   // người tiếp theo\n    for (j = 0; j < n; j++) if (!(mask >> j & 1))\n        dp[mask | 1 << j] = min(dp[mask | 1 << j], dp[mask] + c[i][j]);\n}",
    "why": "Thử mọi hoán vị O(n!·n) chỉ được n ≤ 10; QHĐ bitmask O(2ⁿ·n) = 2·10⁷ với n = 20."},
  "rules": []},
"bm_03": {"flags": {"ll": True},
  "opt": {"slow": ["perm", "recursion"], "name": "QHĐ bitmask TSP dp[mask][u]",
    "idea": "dp[mask][u] = đường ngắn nhất xuất phát 0, đã thăm tập mask, đang ở u.",
    "code": "dp[1][0] = 0;\nfor (mask) for (u in mask) for (v not in mask)\n    dp[mask | 1 << v][v] = min(.., dp[mask][u] + d[u][v]);\nans = min(dp[full][u] + d[u][0]);",
    "why": "Thử mọi hoán vị O(n!) với n = 16 là 2·10¹³; QHĐ O(2ⁿ·n²) = 1,7·10⁷."},
  "rules": []},
}
